### ISSUE TITLE
Operation not permitted - /usr/bin/thor

### ISSUE THREAD

**Issue by Hobbit78** [thoughtbot/bourbon#822] opened 2016-01-23 11:33 UTC
When I try to install Bourbon with `$ sudo gem install Bourbon` it gives me the error:

```bash
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/thor
```

I'm not sure what to do.

Thanks in advance.

**Comment by elomatreb** [comment] 2016-01-23 11:36
This doesn't really address your issue, but it should not be necessary to install gems using `sudo`. Have you looked into installing gems into a directory you own and adding this directory to your PATH?

**Comment by Hobbit78** [comment] 2016-01-23 12:28
Thanks elomatreb.

When not using sudo it gives me this error:

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I have to admit that i'm not a Terminal specialist ;-) 

I hope you can bring me a step firther.

**Comment by tysongach** [comment] 2016-01-23 14:11
This is a duplicate of #820 and likely not directly a Bourbon issue, but more of permissions issue with your local development environment…

Closing this issue in favor of consolidating conversation in #820.

**Closed by tysongach** 2016-01-23 14:11 UTC

**Comment by jeremykenedy** [comment] 2016-06-09 17:55
You closed the issue without resolution and linked it to another answer that was closed due to lack of response. 

Issue not solved @tysongach

**Comment by lab-js** [comment] 2016-07-27 09:55
+1

**Comment by tysongach** [comment] 2016-07-27 14:59
@jeremykenedy @lab-js Are you able to install other gems, or is this isolated to Bourbon? What’s your development environment look like?
