### ISSUE TITLE
Error on selection mixin when using libsass

### ISSUE THREAD

**Issue by jriram** [thoughtbot/bourbon#615] opened 2015-01-08 17:26 UTC
I get the next error message when importing bourbon 4.1.0:

```
_selection.scss:4: error reading values after @if
```
I am using the following with libsass:

```
$ sassc --version
sassc: 3.0.2-16-gfbdc
libsass: 3.1.0
sass2scss: 1.0.3
```
Is Bourbon 4.1.0 compatible with this version of libsass?

**Comment by kaishin** [comment] 2015-01-08 17:40
I can confirm this.

**Comment by kaishin** [comment] 2015-01-08 17:45
Libsass does not support `&` as of `3.1` http://sass-compatibility.github.io/#ampersand_sassscript.

**Comment by will3** [comment] 2015-01-11 17:09
I get the same error when using gulp-sass version `1.2.4` (https://www.npmjs.com/package/gulp-sass).

**Comment by andrewcroce** [comment] 2015-01-13 19:14
Confirming this as well

**Comment by filp** [comment] 2015-01-14 16:36
Also experiencing this :+1:

**Comment by gitawego** [comment] 2015-01-14 20:57
I can confirm this as well with sass-loader in webpack.

**Comment by gosukiwi** [comment] 2015-01-15 08:19
Happens to me too, `$ cat Gemfile.lock | grep sass` returns

```
      sass (~> 3.3)
      jekyll-sass-converter (~> 1.0)
      sass (~> 3.2)
      sprockets-sass
    jekyll-sass-converter (1.0.0)
      sass (~> 3.2)
      sass (>= 3.3)
    sass (3.3.8)
    sprockets-sass (1.3.1)
  sass
```

**Comment by felixbuenemann** [comment] 2015-01-15 15:06
This also breaks sass 3.3 compatibility, it only works with sass 3.4.

**Comment by tysongach** [comment] 2015-01-16 16:16
Please note that we still [suggest using Bourbon 3.2.3 with LibSass](https://github.com/thoughtbot/bourbon#requirements).

That being said, there’s [already a PR up](https://github.com/thoughtbot/bourbon/pull/616) to refactor the `selection` mixin to work with LibSass.

**Comment by felixbuenemann** [comment] 2015-01-16 23:55
@tysongach The problem is that the current implementation also throws an exception on the latest version of sass 3.3, while the Gemfile claims to be compatible with sass 3.3+.

**Comment by javierjulio** [comment] 2015-01-22 21:28
@tysongach, yes @felixbuenemann is right. My Rails 4.2 app now using Bourbon (4.1.1) and sass (3.3.14) and I'm receiving a similar error: `Invalid CSS after " @if ": expected expression (e.g. 1px, bold), was "& {"`

**Comment by tysongach** [comment] 2015-01-22 21:31
@javierjulio LibSass compatibility will be [fixed](https://github.com/thoughtbot/bourbon/pull/616) in v4.2.

**Comment by tysongach** [comment] 2015-01-22 23:14
A fix has been merged into `master` and we’ll release v4.2.0 soon.

**Closed by tysongach** 2015-01-22 23:14 UTC
Labels: bug

**Comment by javierjulio** [comment] 2015-01-22 23:17
Awesome, thanks @tysongach!

**Comment by jgodi** [comment] 2015-01-27 18:30
Thanks for the fix, any update on 4.2 release date?

**Comment by joaomilho** [comment] 2015-01-27 22:02
"I get the same error when using gulp-sass version 1.2.4 (https://www.npmjs.com/package/gulp-sass).
Edit: the latest version 1.3.1 fixes this issue."

I'm using gulp-sass 1.3.2 and I have the issue. What can I do?

**Comment by whoughton** [comment] 2015-01-30 17:36
@joaomilho I’m testing this out for myself, but it seems like the best bet for you is to switch from gulp-sass to gulp-ruby-sass.

**Comment by mark-schaal** [comment] 2015-07-23 15:41
I can confirm I am experiencing the same issue with gulp-sass@2.0.4. @joaomilho  did using gulp-ruby-sass work for you?

**Comment by mark-schaal** [comment] 2015-07-23 18:31
FYI, gulp-ruby-sass doesn't support globbing...bit a of a deal breaker on that front.
