### ISSUE TITLE
background and background-image has found an error in the mixin.

### ISSUE THREAD

**Issue by gjjoo** [thoughtbot/bourbon#816] opened 2016-01-14 18:13 UTC
`background` and `background-image` has found an error in the mixin.

```scss
.box {
  @include background(linear-gradient(red, green) left repeat);
  @include background(linear-gradient(red, green) left repeat, radial-gradient(red, orange));
  @include background(url("/images/a.png"), linear-gradient(red, green), center no-repeat orange scroll);
}
```

```css
.box {
  background: linear-gradient(red, green);
  background: linear-gradient(red, green), radial-gradient(red, orange);
  background: url("/images/a.png"), linear-gradient(red, green), center;
}
```

In the output results are not visible attributes such as `left` and `repeat`.

The `_background.scss` and `_background-image.scss` was resolved by modifying the file, as follows:
```scss
// ...
//@each $background in $backgrounds {
@for $i from 1 through length($backgrounds) {
  $background: nth($backgrounds, $i);
// ...
```

After modifying the output results:
```css
.box {
  background: linear-gradient(red, green) left repeat;
  background: linear-gradient(red, green) left repeat, radial-gradient(red, orange);
  background: url("/images/a.png"), linear-gradient(red, green), center no-repeat orange scroll;
}
```

Check, please.

**Comment by tysongach** [comment] 2016-01-26 03:16
Hi @gjjoo! I’m unable to re-create this issue you’re having. Here’s a CodePen test: http://codepen.io/tysongach/pen/ZQxeNq?editors=0100

I’m going to close this for now, but please re-open if the problem persists (with some insight into your development environment).

**Comment by blacktorn** [comment] 2016-01-27 13:57
@tysongach It's happening when you use a recent (v3.3.2) libsass:
http://www.sassmeister.com/gist/2c61a16422b08fa49100

**Comment by gjjoo** [comment] 2016-01-27 14:16
@blacktorn Thank you for your reply..!!

**Comment by benjdl** [comment] 2016-03-07 15:28
Hi,
Any news on this problem? I encounter the same bug (Sass 3.4.21, Bourbon 4.2.6).

**Comment by tysongach** [comment] 2016-04-14 12:39
@gjjoo @blacktorn @benjdl The issue appears to be a regression in LibSass when using `@each` to iterate over selector lists (as we do in `background()` and `background-image()`). Here’s the specific commit where they resolved the issue: https://github.com/sass/libsass/commit/cfc4e82f95f61395401a8f801434927c861cdddd

Upgrading to LibSass 3.3.3 or 3.3.4 should resolve the issue. It looks like the `sassc` gem is already updated to the latest LibSass and I believe `node-sass` is up to LibSass 3.3.3 in its beta. That being said, I think Sassmeister and likely CodePen are both still wrapping LibSass 3.3.2 which has this bug.

Hope that helps!

**Closed by tysongach** 2016-04-14 12:39 UTC
Labels: v4
