### ISSUE TITLE
Border color linear-gradient

### ISSUE THREAD

**Issue by peterpeterparker** [thoughtbot/bourbon#936] opened 2016-09-07 09:49 UTC
First of all, thx for the cool library, really useful!

Maybe I missed it, but there is no way to use the linear-gradient to define border-color right?

I want to achieve rounded buttons, with no background (or transparent) and with a linear-gradient as border color. If that would be possible with bourbon, that would be awesome

**Comment by abea** [comment] 2016-09-07 14:06
It looks like the [`border-image`](http://bourbon.io/docs/#border-image) mixin is all set up to handle linear or radial gradient borders: https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/css3/_border-image.scss#L23-L27.

**Comment by peterpeterparker** [comment] 2016-09-07 14:23
Didn't worked for me. I tried 

    mybuttonclass {
        @include border-image(linear-gradient(to bottom, white, red));
        border-width: 10px;
    }

and I ended up with a weird button with a gradient square on every corner of the button...

<img width="135" alt="capture d ecran 2016-09-07 a 16 23 23" src="https://cloud.githubusercontent.com/assets/16886711/18315475/6cf58986-7517-11e6-8373-20953f954ec1.png">

**Comment by whmii** [comment] 2016-09-07 14:40
@peterpeterparker That's basically working as intended. The real trick is that what you are trying to do may just be too complex for the mixin to handle, since all it's doing is some prefixing and defaults. Check out this post on css linear gradient boarders https://css-tricks.com/examples/GradientBorder from @css-tricks

Unfortunately css borders with gradients is barely possible.

**Comment by whmii** [comment] 2016-09-07 14:59
@peterpeterparker I made a CodePen of what you were trying to put together. You probably want to just write this out in vanilla css.

http://codepen.io/whmii/pen/qadqwk

```css
    border-width: 3px;
    border-style: solid;
    border-image: linear-gradient(to bottom left, black, orange) 0.5 stretch;
```

**Comment by peterpeterparker** [comment] 2016-09-07 15:39
thx for the example @whmii !

looks good on Chrome but unfortunately doesn't work for me on Safari :(

right now I could solve my designer issue with a span inside a little bit bigger button with both a different background color (button = background gradient, span background white for example). 

but still would be cleaner to do it with a bourbon's mixin.

**Comment by tysongach** [comment] 2016-09-15 20:16
I’m going to close this issue as it relates to CSS features and less about an issue with Bourbon. The `border-image` mixin was meant to handle prefixes, but we’ve moved away from that strategy.

**Closed by tysongach** 2016-09-15 20:16 UTC
