### ISSUE TITLE
_transition.scss add "filter" multibrowsers

### ISSUE THREAD

**Issue by soulcreate** [thoughtbot/bourbon#760] opened 2015-07-31 08:29 UTC
Please add prefixes to "filter" transition:
```
transition: 1s filter linear;
-webkit-transition: 1s -webkit-filter linear;
-moz-transition: 1s -moz-filter linear;
-ms-transition: 1s -ms-filter linear;
-o-transition: 1s -o-filter linear;
```

**Comment by tysongach** [comment] 2015-07-31 15:23
This is a duplicate of #750.

**Closed by tysongach** 2015-07-31 15:23 UTC
